# database configuration
spring:
#  datasource.url: jdbc:postgresl://ec2-34-206-252-187.compute-1.amazonaws.com/ddm9b67hski2lu?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
  datasource.url: jdbc:postgresql://localhost:5432/panda_diary
#  datasource.username: snvlgphqusfcyw
#  datasource.password: 7796d737e7d9cd0f336b4d8b0e09ef1e35e951b594198bf8f7b4729589ff785f
  datasource.username: pandiary
  datasource.password: Pa55w0rd
  datasource.driver-class-name: org.postgresql.Driver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: update
  jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
