# database configuration
spring:
  datasource.url: jdbc:postgresl://ec2-52-201-55-4.compute-1.amazonaws.com/d24bt3ho5u0dj1?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
#  datasource.url: jdbc:postgresql://localhost:5432/panda_diary
  datasource.username: foyyhuyqiqqmbk
  datasource.password: 04b1a5dfc6627aab8aaf5b3cd67e3dbd7832a33a58d92bfce561197e958d108e
#  datasource.username: pandiary
#  datasource.password: Pa55w0rd
  datasource.driver-class-name: org.postgresql.Driver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: update
  jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
